### ISSUE TITLE
How can I get JavaScript source code to show up nicely?

### ISSUE THREAD

**Issue by epsitec** [tanksuzuki/angels-ladder#6]
I've noticed that if I use ```json in my markdown, it gets rendered nicely on a black background:

![github1](https://cloud.githubusercontent.com/assets/3872435/11211695/923695f6-8d31-11e5-990e-c8dd364cf782.png)

However, if I try to use ```javascript I was expecting the same to happen with JavaScript and matching syntax highlighting. But instead, I get this:

![github2](https://cloud.githubusercontent.com/assets/3872435/11211697/97ff9780-8d31-11e5-8bd7-7170b249ff82.png)

Did I miss something?

**Comment by yoichitgy** [comment]
You can replace `static/js/highlight.pack.js` with another one including JavaScript syntax, or just try the branch referenced by Pull Request #4.

If you would like to use your own choices of languages, you can choose the languages and download a generated js file [here](https://highlightjs.org/download/)

**Comment by epsitec** [comment]
I was not aware of the `highlightjs.org` - that's a great resource. Thank you for pointing to it, a new treasure trove...
